# MamaFern Headless Storefront App
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "${SHOPIFY_API_KEY}"
name = "mama-fern"
application_url = "http://localhost:3001"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev = "npm run dev"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Headless storefront scopes for reading products and customer data
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders,write_customers,read_customers"

[auth]
redirect_urls = [ "http://localhost:3001/api/auth/callback" ]
